version: '3.8'

services:

  kafka:
    image: apache/kafka:4.3.0
    container_name: kafka
    restart: "no"
    ports:
      - "9092:9092"
      - "7071:7071"

    environment:

      # -----------------------------
      # KRaft
      # -----------------------------
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # -----------------------------
      # Single node settings
      # -----------------------------
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # -----------------------------
      # Storage
      # -----------------------------
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # -----------------------------
      # Heap & JVM tuning
      # -----------------------------
      KAFKA_HEAP_OPTS: "-Xms4G -Xmx4G"
      KAFKA_JVM_PERFORMANCE_OPTS: >
        -server
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=20
        -XX:InitiatingHeapOccupancyPercent=35
        -XX:+ExplicitGCInvokesConcurrent
        -Djava.awt.headless=true

      # -----------------------------
      # JMX Exporter
      # -----------------------------
      KAFKA_OPTS: >
        -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=7071:/opt/jmx-exporter/kafka.yml


    volumes:
      # Kafka persistent storage
      - ./_volume:/var/lib/kafka/data

      # JMX exporter jar
      - ../assets/jmx_prometheus_javaagent-1.5.0.jar:/opt/jmx-exporter/jmx_prometheus_javaagent.jar:ro

      # JMX exporter config
      - ./kafka/kafka.yml:/opt/jmx-exporter/kafka.yml:ro


  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.9.0
    container_name: kafka-exporter
    restart: "no"
    depends_on:
      - kafka

    ports:
      - "9308:9308"

    command:
      - "--kafka.server=kafka:9092"

      # Log errors & warnings only
      - "--verbosity=1"

      # Enable consumer group metrics
      - "--group.filter=.*"

      # Enable topic metrics
      - "--topic.filter=.*"