##############################
# KRaft Mode
##############################

# Unique broker/controller ID
KAFKA_NODE_ID=1

# Run as both broker + controller (single-node KRaft)
KAFKA_PROCESS_ROLES=broker,controller

# Listener used by controller quorum
KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER

# Controller quorum configuration
# Format:
# <node-id>@<host>:<controller-port>
KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9094



##############################
# Kafka Listeners
##############################

# Bind listeners inside container
#
# INTERNAL   -> container-to-container communication
# EXTERNAL   -> host machine clients
# CONTROLLER -> KRaft controller communication
KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094


# Addresses advertised to clients
#
# kafka:9092     -> used by Docker containers
# localhost:9093 -> used by host machine apps
KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093


# Protocol mapping for each listener
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT


# Listener used for broker-to-broker communication
KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL



##############################
# Topic Replication
##############################

# Internal topic replication factor
# Keep as 1 for single-node Kafka
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

# Transaction state topic replication factor
KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1

# Minimum in-sync replicas for transaction topic
KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1



##############################
# Storage
##############################

# Kafka log/data directory inside container
KAFKA_LOG_DIRS=/var/lib/kafka/data

# Unique KRaft cluster ID
# Generated once and reused permanently
CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
