# `dw` file name prefix means: data-weave

# =========================
# App server configs
# =========================
spring.application.name=dataweave-api-json
server.port=9111
kafka.producer.worker-count=4

# Keep the below b/w 0.0 to 1.0
log.probability=0.2


# =========================
# logging configs when running locally
# =========================
logging.file.name=/app/logs/web.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7


# =========================
# Spring Kafka
# =========================
spring.kafka.bootstrap-servers=10.0.1.57:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

# Wait up to 20ms to accumulate records into a batch
# spring.kafka.producer.properties.linger.ms=20
spring.kafka.producer.properties.linger.ms=0


# Maximum batch size in bytes (16 KB)
spring.kafka.producer.properties.batch.size=16384

# Compress the msg
# spring.kafka.producer.properties.compression.type=zstd
spring.kafka.producer.properties.compression.type=none



# =========================
# Schema registry
# =========================
schema.registry.url=http://10.0.1.57:8081


# =========================
# Monitoring
# =========================
# Expose Prometheus actuator endpoint
management.endpoints.web.exposure.include=health,info,prometheus
# Enable Prometheus export (default true)
management.metrics.export.prometheus.enabled=true
# Optional: add common tags
management.metrics.tags.application=kafka-producer-app