---
- name: Copy Spring-app properties file per app-server
  hosts: app_server
  become: true

  vars:
    dest_dir: /home/ubuntu/data-weave/web/src/main/resources

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        mode: "0755"

    - name: Copy for JSON app-node
      copy:
        src: ../assets/dw-json-application-docker.properties
        dest: "{{ dest_dir }}/application-docker.properties"
        mode: "0644"
      when: inventory_hostname == "app_server_1"

    - name: Copy for AVRO app-node
      copy:
        src: ../assets/dw-avro-application-docker.properties
        dest: "{{ dest_dir }}/application-docker.properties"
        mode: "0644"
      when: inventory_hostname == "app_server_2"