---
- import_playbook: flush_prom_server_volume.yml
- import_playbook: sleep.yml

- import_playbook: flush_app_node_data.yml
- import_playbook: flush_kafka_node_data.yml

- import_playbook: flush_prom_server_volume.yml
- import_playbook: sleep.yml

- import_playbook: start_app_container.yml
