app_server:
  hosts:
    app_server_1:
      ansible_host: 10.0.1.220

  # common var for each host above
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/ap-south-keypair-1.pem


kafka_node:
  hosts:
    kafka_node_1:
      ansible_host: 10.0.1.246
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/ap-south-keypair-1.pem


monitoring:
  hosts:
    localhost:
      ansible_connection: local
